"""Tests for the heroku-to-aws migration-report.html validator."""

from __future__ import annotations

import json
import subprocess  # nosec B404 — test-only, list args, no shell, committed script path
import sys
import tempfile
from pathlib import Path

SCRIPT = Path(__file__).resolve().parent / "validate-heroku-migration-report.py"


def run(html: str, migration_dir: Path | None = None) -> tuple[int, str]:
    with tempfile.TemporaryDirectory() as tmp:
        report = Path(tmp) / "migration-report.html"
        report.write_text(html, encoding="utf-8")
        cmd = [sys.executable, str(SCRIPT), str(report)]
        if migration_dir is not None:
            cmd += ["--migration-dir", str(migration_dir)]
        result = subprocess.run(cmd, capture_output=True, text=True)  # nosec B603
        return result.returncode, result.stdout + result.stderr


# A minimal but complete, compliant Heroku report.
GOOD = """<!DOCTYPE html>
<html lang="en">
<body>
<div class="report">
  <section id="decision-summary"><p class="verdict-headline">Go, with conditions</p></section>
  <section id="exec-costs"><table><thead><tr><th scope="col">Tier</th></tr></thead><tbody><tr><td>Balanced</td></tr></tbody></table></section>
  <section id="cost-optimization"><p>No 1-year/3-year commitment product applies to this architecture.</p></section>
  <section id="next-steps"><ol><li>See MIGRATION_GUIDE.md</li></ol></section>
  <footer>Generated by Heroku to AWS Migration Advisor — draft for review; verify figures before executive sign-off.</footer>
</div>
</body>
</html>
"""


def _rec_dir(tmp: str) -> Path:
    d = Path(tmp)
    (d / "estimation-infra.json").write_text(
        json.dumps({"recommendation": {"outcome": "go_conditional"}}), encoding="utf-8"
    )
    return d


def test_good_report_passes() -> None:
    code, out = run(GOOD)
    assert code == 0, out
    assert "REPORT_OK" in out


def test_missing_cost_optimization_fails() -> None:
    html = GOOD.replace(
        '<section id="cost-optimization"><p>No 1-year/3-year commitment product applies to this architecture.</p></section>',
        "",
    )
    code, out = run(html)
    assert code == 1, out
    assert "cost-optimization" in out


def test_missing_draft_footer_fails() -> None:
    html = GOOD.replace("draft for review; verify figures before executive sign-off.", "")
    code, out = run(html)
    assert code == 1, out
    assert "draft for review" in out.lower()


def test_badge_verdict_pill_fails() -> None:
    html = GOOD.replace(
        '<p class="verdict-headline">Go, with conditions</p>',
        '<span class="badge-verdict-go">Go</span>',
    )
    code, out = run(html)
    assert code == 1, out
    assert "badge-verdict" in out.lower() or "verdict-headline" in out.lower()


def test_th_without_scope_fails() -> None:
    html = GOOD.replace('<th scope="col">Tier</th>', "<th>Tier</th>")
    code, out = run(html)
    assert code == 1, out
    assert "scope" in out.lower()


def test_missing_html_lang_fails() -> None:
    html = GOOD.replace('<html lang="en">', "<html>")
    code, out = run(html)
    assert code == 1, out
    assert "lang" in out.lower()


def test_verdict_headline_required_when_recommendation_outcome_present() -> None:
    # No verdict-headline in decision-summary; recommendation.outcome is declared → FAIL.
    html = GOOD.replace(
        '<p class="verdict-headline">Go, with conditions</p>',
        "<p>Go, with conditions</p>",
    )
    with tempfile.TemporaryDirectory() as tmp:
        code, out = run(html, migration_dir=_rec_dir(tmp))
    assert code == 1, out
    assert "verdict-headline" in out.lower()


def test_verdict_headline_not_required_without_recommendation() -> None:
    # Same HTML, but no estimation-infra.json recommendation → the headline
    # requirement does not fire (the plain-text verdict is allowed).
    html = GOOD.replace(
        '<p class="verdict-headline">Go, with conditions</p>',
        "<p>Go, with conditions</p>",
    )
    code, out = run(html)
    assert code == 0, out
    assert "REPORT_OK" in out


def test_what_if_required_when_two_scenarios() -> None:
    with tempfile.TemporaryDirectory() as tmp:
        d = Path(tmp)
        (d / "scenarios").mkdir()
        (d / "scenarios" / "index.json").write_text(
            json.dumps({"scenarios": [{"id": "a"}, {"id": "b"}]}), encoding="utf-8"
        )
        code, out = run(GOOD, migration_dir=d)
    assert code == 1, out
    assert "what-if-scenarios" in out


def test_good_report_with_recommendation_passes() -> None:
    # Happy path WITH a declared outcome: the verdict-headline is present, so the
    # recommendation-gated requirement is satisfied and the report passes.
    with tempfile.TemporaryDirectory() as tmp:
        code, out = run(GOOD, migration_dir=_rec_dir(tmp))
    assert code == 0, out
    assert "REPORT_OK" in out


def test_empty_cost_optimization_fails() -> None:
    html = GOOD.replace(
        '<section id="cost-optimization"><p>No 1-year/3-year commitment product applies to this architecture.</p></section>',
        '<section id="cost-optimization"></section>',
    )
    code, out = run(html)
    assert code == 1, out
    assert "cost-optimization" in out and "empty" in out.lower()


def test_heading_only_cost_optimization_fails() -> None:
    # A heading alone (no opportunity table, no no-eligible-commitment sentence)
    # must not satisfy the content requirement.
    html = GOOD.replace(
        '<section id="cost-optimization"><p>No 1-year/3-year commitment product applies to this architecture.</p></section>',
        '<section id="cost-optimization"><h2>Cost Optimization Opportunities</h2></section>',
    )
    code, out = run(html)
    assert code == 1, out
    assert "cost-optimization" in out


def test_table_headers_only_cost_optimization_fails() -> None:
    # A table with column headers but an empty <tbody> — no actual opportunity
    # rows — must not satisfy the content requirement either.
    html = GOOD.replace(
        '<section id="cost-optimization"><p>No 1-year/3-year commitment product applies to this architecture.</p></section>',
        '<section id="cost-optimization"><table><thead><tr>'
        '<th scope="col">Opportunity</th><th scope="col">Savings</th>'
        "</tr></thead><tbody></tbody></table></section>",
    )
    code, out = run(html)
    assert code == 1, out
    assert "cost-optimization" in out


def test_cost_optimization_with_real_opportunity_row_passes() -> None:
    # Control: an actual populated row in the tbody is real content and passes.
    html = GOOD.replace(
        '<section id="cost-optimization"><p>No 1-year/3-year commitment product applies to this architecture.</p></section>',
        '<section id="cost-optimization"><table><thead><tr>'
        '<th scope="col">Opportunity</th></tr></thead><tbody><tr>'
        "<td>1yr Compute Savings Plan: ~25%</td></tr></tbody></table></section>",
    )
    code, out = run(html)
    assert code == 0, out
    assert "REPORT_OK" in out


def test_empty_tbody_with_credits_disclaimer_fails() -> None:
    # Regression: an empty <tbody> plus the credits disclaimer prose that normally
    # accompanies a populated table must NOT satisfy the content check on its own —
    # the disclaimer is explanatory text, not an opportunity row or the explicit
    # no-eligible-commitment sentence.
    html = GOOD.replace(
        '<section id="cost-optimization"><p>No 1-year/3-year commitment product applies to this architecture.</p></section>',
        '<section id="cost-optimization"><table><thead><tr>'
        '<th scope="col">Optimization</th></tr></thead><tbody></tbody></table>'
        "<p>Activate credits don't cover RI/Savings Plan upfront costs — they apply "
        "only to the ongoing discounted hourly rate.</p></section>",
    )
    code, out = run(html)
    assert code == 1, out
    assert "cost-optimization" in out


def test_th_only_row_in_tbody_does_not_count_as_opportunity_row() -> None:
    # A <tbody> row made only of <th> cells (no <td>) must not count as a
    # populated opportunity row.
    html = GOOD.replace(
        '<section id="cost-optimization"><p>No 1-year/3-year commitment product applies to this architecture.</p></section>',
        '<section id="cost-optimization"><table><thead><tr>'
        '<th scope="col">Opportunity</th></tr></thead><tbody><tr>'
        '<th scope="row">Totals</th></tr></tbody></table></section>',
    )
    code, out = run(html)
    assert code == 1, out
    assert "cost-optimization" in out


def test_nbsp_only_opportunity_cell_fails() -> None:
    # Regression: a <td> whose only content is a non-breaking-space entity is
    # visually blank. Raw-source matching sees "&nbsp;" as non-empty literal
    # text; a parser that decodes character references first correctly treats
    # it as blank.
    html = GOOD.replace(
        '<section id="cost-optimization"><p>No 1-year/3-year commitment product applies to this architecture.</p></section>',
        '<section id="cost-optimization"><table><tbody><tr>'
        "<td>&nbsp;</td></tr></tbody></table></section>",
    )
    code, out = run(html)
    assert code == 1, out
    assert "cost-optimization" in out


def test_numeric_charref_only_opportunity_cell_fails() -> None:
    # Same as above but with the numeric character reference form (&#160;)
    # rather than the named entity.
    html = GOOD.replace(
        '<section id="cost-optimization"><p>No 1-year/3-year commitment product applies to this architecture.</p></section>',
        '<section id="cost-optimization"><table><tbody><tr>'
        "<td>&#160;</td></tr></tbody></table></section>",
    )
    code, out = run(html)
    assert code == 1, out
    assert "cost-optimization" in out


def test_commented_out_opportunity_row_fails() -> None:
    # Regression: a real opportunity row that is commented out in the HTML
    # source must not count. A regex scanning raw source can match inside an
    # HTML comment; a parser naturally routes comment text away from
    # handle_data.
    html = GOOD.replace(
        '<section id="cost-optimization"><p>No 1-year/3-year commitment product applies to this architecture.</p></section>',
        '<section id="cost-optimization"><table><tbody>'
        "<!-- <tr><td>RDS Reserved Instance</td></tr> --></tbody></table></section>",
    )
    code, out = run(html)
    assert code == 1, out
    assert "cost-optimization" in out


def test_opportunity_row_without_explicit_tbody_passes() -> None:
    # Regression: <table><tr><td>...</td></tr></table> with no <tbody> tag at
    # all is valid HTML (an implicit tbody is inferred) and a real opportunity
    # row inside it must still count as content.
    html = GOOD.replace(
        '<section id="cost-optimization"><p>No 1-year/3-year commitment product applies to this architecture.</p></section>',
        '<section id="cost-optimization"><table><tr>'
        "<td>RDS Reserved Instance</td></tr></table></section>",
    )
    code, out = run(html)
    assert code == 0, out
    assert "REPORT_OK" in out


def test_opportunity_row_with_omitted_td_end_tag_passes() -> None:
    # Regression: the HTML Standard permits a <td> end tag to be omitted
    # immediately before the parent </tr>. A compact, perfectly valid table
    # with no </td> at all must still register its real content — the old
    # parser only finalized a cell on an EXPLICIT handle_endtag("td"), so this
    # exact shape silently registered as empty and failed a valid report.
    html = GOOD.replace(
        '<section id="cost-optimization"><p>No 1-year/3-year commitment product applies to this architecture.</p></section>',
        '<section id="cost-optimization"><table><tr>'
        "<td>RDS Reserved Instance</tr></table></section>",
    )
    code, out = run(html)
    assert code == 0, out
    assert "REPORT_OK" in out


def test_opportunity_row_with_sibling_omitted_td_end_tags_passes() -> None:
    # Two sibling cells in the same row, both with omitted end tags — the
    # second cell's start tag implicitly closes the first. The real
    # opportunity text in the second cell must still be found.
    html = GOOD.replace(
        '<section id="cost-optimization"><p>No 1-year/3-year commitment product applies to this architecture.</p></section>',
        '<section id="cost-optimization"><table><tr>'
        "<td>Opportunity<td>RDS Reserved Instance</tr></table></section>",
    )
    code, out = run(html)
    assert code == 0, out
    assert "REPORT_OK" in out


def test_opportunity_row_with_omitted_td_end_tag_blank_cell_still_fails() -> None:
    # Control: an omitted end tag on a genuinely BLANK cell must not
    # accidentally start passing just because the end tag is optional —
    # only real, nonblank text should ever satisfy this check.
    html = GOOD.replace(
        '<section id="cost-optimization"><p>No 1-year/3-year commitment product applies to this architecture.</p></section>',
        '<section id="cost-optimization"><table><tr><td></tr></table></section>',
    )
    code, out = run(html)
    assert code == 1, out
    assert "cost-optimization" in out


def test_th_scope_with_spaces_around_equals_passes() -> None:
    # scope = "col" (spaces around =) is valid HTML and must be accepted —
    # a literal `scope="col"` regex would wrongly reject it.
    html = GOOD.replace('<th scope="col">Tier</th>', '<th scope = "col">Tier</th>')
    code, out = run(html)
    assert code == 0, out
    assert "REPORT_OK" in out


def test_th_scope_unquoted_passes() -> None:
    # scope=col (unquoted attribute value) is valid HTML and must be accepted.
    html = GOOD.replace('<th scope="col">Tier</th>', "<th scope=col>Tier</th>")
    code, out = run(html)
    assert code == 0, out
    assert "REPORT_OK" in out


def test_th_scope_single_quoted_passes() -> None:
    html = GOOD.replace('<th scope="col">Tier</th>', "<th scope='col'>Tier</th>")
    code, out = run(html)
    assert code == 0, out
    assert "REPORT_OK" in out


def test_html_lang_with_spaces_around_equals_passes() -> None:
    html = GOOD.replace('<html lang="en">', '<html lang = "en">')
    code, out = run(html)
    assert code == 0, out
    assert "REPORT_OK" in out


def test_figure_aria_label_unquoted_passes() -> None:
    html = GOOD.replace(
        "</div>",
        "<figure aria-label=Costs><figcaption>Costs</figcaption></figure></div>",
    )
    code, out = run(html)
    assert code == 0, out
    assert "REPORT_OK" in out


def test_figure_without_aria_label_fails() -> None:
    html = GOOD.replace("</div>", "<figure><figcaption>Costs</figcaption></figure></div>")
    code, out = run(html)
    assert code == 1, out
    assert "aria-label" in out.lower()


def test_figure_with_aria_label_and_figcaption_passes() -> None:
    html = GOOD.replace(
        "</div>",
        '<figure aria-label="Cost breakdown"><figcaption>Costs</figcaption></figure></div>',
    )
    code, out = run(html)
    assert code == 0, out
    assert "REPORT_OK" in out


def test_verdict_headline_with_spaces_around_equals_passes() -> None:
    # class = "verdict-headline" (spaces around =) is valid HTML and must be
    # accepted when recommendation.outcome is declared.
    html = GOOD.replace(
        '<p class="verdict-headline">Go, with conditions</p>',
        '<p class = "verdict-headline">Go, with conditions</p>',
    )
    with tempfile.TemporaryDirectory() as tmp:
        code, out = run(html, migration_dir=_rec_dir(tmp))
    assert code == 0, out
    assert "REPORT_OK" in out


def test_verdict_headline_unquoted_passes() -> None:
    # class=verdict-headline (unquoted, single token) is valid HTML and must be
    # accepted when recommendation.outcome is declared.
    html = GOOD.replace(
        '<p class="verdict-headline">Go, with conditions</p>',
        "<p class=verdict-headline>Go, with conditions</p>",
    )
    with tempfile.TemporaryDirectory() as tmp:
        code, out = run(html, migration_dir=_rec_dir(tmp))
    assert code == 0, out
    assert "REPORT_OK" in out


def test_badge_verdict_pill_with_spaces_around_equals_fails() -> None:
    # class = "badge-verdict-go" (spaces around =) is valid, equivalent HTML and
    # must still be caught by the badge ban — it must not bypass the check by
    # using different (but legal) attribute formatting.
    html = GOOD.replace(
        '<p class="verdict-headline">Go, with conditions</p>',
        '<p class="verdict-headline">Go, with conditions</p>'
        '<span class = "badge-verdict-go">Go</span>',
    )
    code, out = run(html)
    assert code == 1, out
    assert "badge-verdict" in out.lower()


def test_badge_verdict_pill_unquoted_fails() -> None:
    # class=badge-verdict-go (unquoted) must also be caught — regression for the
    # gap where a badge alongside a normal headline returned REPORT_OK because
    # the literal `class="..."` regex didn't match unquoted attribute syntax.
    html = GOOD.replace(
        '<p class="verdict-headline">Go, with conditions</p>',
        '<p class="verdict-headline">Go, with conditions</p>'
        "<span class=badge-verdict-go>Go</span>",
    )
    code, out = run(html)
    assert code == 1, out
    assert "badge-verdict" in out.lower()


def test_figure_without_figcaption_fails() -> None:
    """A <figure> with aria-label but no <figcaption> fails (symmetric to the aria-label case)."""
    html = GOOD.replace("</div>", '<figure aria-label="Costs">chart</figure></div>')
    code, out = run(html)
    assert code == 1, out
    assert "figcaption" in out.lower()


def test_validator_is_packaged_inside_the_skill_directory() -> None:
    """The validator must live under skills/heroku-to-aws/ so a standalone
    `npx skills add --skill heroku-to-aws` install (which copies only this
    skill's own directory tree, not the plugin's top-level scripts/) still
    carries it. Regression for the packaging gap where the validator lived at
    the plugin root and Generate's `$PLUGIN_ROOT/scripts/...` invocation had
    nothing to resolve against in a skill-only install."""
    assert SCRIPT.is_file()
    assert SCRIPT.parent.name == "scripts"
    assert SCRIPT.parent.parent.name == "heroku-to-aws"
    assert SCRIPT.parent.parent.parent.name == "skills"
