"""Tests for the heroku-to-aws migration-report.html validator."""

from __future__ import annotations

import json
import subprocess
import sys
import tempfile
from pathlib import Path

PLUGIN_ROOT = Path(__file__).resolve().parents[1]
SCRIPT = PLUGIN_ROOT / "scripts" / "validate-heroku-migration-report.py"


def run(html: str, migration_dir: Path | None = None) -> tuple[int, str]:
    with tempfile.TemporaryDirectory() as tmp:
        report = Path(tmp) / "migration-report.html"
        report.write_text(html, encoding="utf-8")
        cmd = [sys.executable, str(SCRIPT), str(report)]
        if migration_dir is not None:
            cmd += ["--migration-dir", str(migration_dir)]
        result = subprocess.run(cmd, capture_output=True, text=True)  # nosec B603
        return result.returncode, result.stdout + result.stderr


# A minimal but complete, compliant Heroku report.
GOOD = """<!DOCTYPE html>
<html lang="en">
<body>
<div class="report">
  <section id="decision-summary"><p class="verdict-headline">Go, with conditions</p></section>
  <section id="exec-costs"><table><thead><tr><th scope="col">Tier</th></tr></thead><tbody><tr><td>Balanced</td></tr></tbody></table></section>
  <section id="cost-optimization"><p>No 1-year/3-year commitment product applies to this architecture.</p></section>
  <section id="next-steps"><ol><li>See MIGRATION_GUIDE.md</li></ol></section>
  <footer>Generated by Heroku to AWS Migration Advisor — draft for review; verify figures before executive sign-off.</footer>
</div>
</body>
</html>
"""


def _rec_dir(tmp: str) -> Path:
    d = Path(tmp)
    (d / "estimation-infra.json").write_text(
        json.dumps({"recommendation": {"outcome": "go_conditional"}}), encoding="utf-8"
    )
    return d


def test_good_report_passes() -> None:
    code, out = run(GOOD)
    assert code == 0, out
    assert "REPORT_OK" in out


def test_missing_cost_optimization_fails() -> None:
    html = GOOD.replace(
        '<section id="cost-optimization"><p>No 1-year/3-year commitment product applies to this architecture.</p></section>',
        "",
    )
    code, out = run(html)
    assert code == 1, out
    assert "cost-optimization" in out


def test_missing_draft_footer_fails() -> None:
    html = GOOD.replace("draft for review; verify figures before executive sign-off.", "")
    code, out = run(html)
    assert code == 1, out
    assert "draft for review" in out.lower()


def test_badge_verdict_pill_fails() -> None:
    html = GOOD.replace(
        '<p class="verdict-headline">Go, with conditions</p>',
        '<span class="badge-verdict-go">Go</span>',
    )
    code, out = run(html)
    assert code == 1, out
    assert "badge-verdict" in out.lower() or "verdict-headline" in out.lower()


def test_th_without_scope_fails() -> None:
    html = GOOD.replace('<th scope="col">Tier</th>', "<th>Tier</th>")
    code, out = run(html)
    assert code == 1, out
    assert "scope" in out.lower()


def test_missing_html_lang_fails() -> None:
    html = GOOD.replace('<html lang="en">', "<html>")
    code, out = run(html)
    assert code == 1, out
    assert "lang" in out.lower()


def test_verdict_headline_required_when_recommendation_outcome_present() -> None:
    # No verdict-headline in decision-summary; recommendation.outcome is declared → FAIL.
    html = GOOD.replace(
        '<p class="verdict-headline">Go, with conditions</p>',
        "<p>Go, with conditions</p>",
    )
    with tempfile.TemporaryDirectory() as tmp:
        code, out = run(html, migration_dir=_rec_dir(tmp))
    assert code == 1, out
    assert "verdict-headline" in out.lower()


def test_verdict_headline_not_required_without_recommendation() -> None:
    # Same HTML, but no estimation-infra.json recommendation → the headline
    # requirement does not fire (the plain-text verdict is allowed).
    html = GOOD.replace(
        '<p class="verdict-headline">Go, with conditions</p>',
        "<p>Go, with conditions</p>",
    )
    code, out = run(html)
    assert code == 0, out
    assert "REPORT_OK" in out


def test_what_if_required_when_two_scenarios() -> None:
    with tempfile.TemporaryDirectory() as tmp:
        d = Path(tmp)
        (d / "scenarios").mkdir()
        (d / "scenarios" / "index.json").write_text(
            json.dumps({"scenarios": [{"id": "a"}, {"id": "b"}]}), encoding="utf-8"
        )
        code, out = run(GOOD, migration_dir=d)
    assert code == 1, out
    assert "what-if-scenarios" in out


def test_good_report_with_recommendation_passes() -> None:
    # Happy path WITH a declared outcome: the verdict-headline is present, so the
    # recommendation-gated requirement is satisfied and the report passes.
    with tempfile.TemporaryDirectory() as tmp:
        code, out = run(GOOD, migration_dir=_rec_dir(tmp))
    assert code == 0, out
    assert "REPORT_OK" in out


def test_empty_cost_optimization_fails() -> None:
    html = GOOD.replace(
        '<section id="cost-optimization"><p>No 1-year/3-year commitment product applies to this architecture.</p></section>',
        '<section id="cost-optimization"></section>',
    )
    code, out = run(html)
    assert code == 1, out
    assert "cost-optimization" in out and "empty" in out.lower()


def test_figure_without_aria_label_fails() -> None:
    html = GOOD.replace("</div>", "<figure><figcaption>Costs</figcaption></figure></div>")
    code, out = run(html)
    assert code == 1, out
    assert "aria-label" in out.lower()


def test_figure_with_aria_label_and_figcaption_passes() -> None:
    html = GOOD.replace(
        "</div>",
        '<figure aria-label="Cost breakdown"><figcaption>Costs</figcaption></figure></div>',
    )
    code, out = run(html)
    assert code == 0, out
    assert "REPORT_OK" in out


def test_figure_without_figcaption_fails() -> None:
    """A <figure> with aria-label but no <figcaption> fails (symmetric to the aria-label case)."""
    html = GOOD.replace("</div>", '<figure aria-label="Costs">chart</figure></div>')
    code, out = run(html)
    assert code == 1, out
    assert "figcaption" in out.lower()
